### ISSUE TITLE
[Question] ser.get(angle.ctrl_mode_, mode); does not return the actual mode

### ISSUE THREAD

**Issue by gon0** [iq-motion-control/iq-module-communication-arduino#9]
**Describe the bug**
Dear IQ-team,
I am not sure if I understood the use of angle.ctrl_mode_ correctly. 
My expectation is: the mode variable can be used to check if the motor is still running its programmed trajectory. This means while running a trajectory, the mode is 6, when finished, the mode goes back to 5.
The actual behaviour is: The motor switches back to 5 before the trajectory is finished while the motor is blocked.

**To Reproduce**
- Arduino 1.8.10
- IQ Motor 220 kV (from Kickstarter campaign) with newest firmware 10
- Slightly changed MultiTurnDemo.ino, see below
- ESP32
- run the sketch
- the motor will turn in one direction for 5 seconds
- the motor will turn in the other direction for 5 seconds
- after 10 seconds, the mode goes from 6 to 5

**now grab the motor and slow down its motion:**
- run the sketch
- the motor will turn in one direction e.g. for 8 seconds
- the motor will turn in the other direction e.g. for 8 seconds
- however, the mode variable will go back to mode == 5, although the motor is still running the trajectory

Code to reproduce error:
```
/* 
 *  IQ multi turn serial demo. 
 *  
 *  This code will command a multi turn controller to go to a position,
 *  then return to the zero position repeatedly.
 *  
 *  The circuit:
 *    Arduino RX is directly connected to motor TX
 *    Arduino TX is directly connected to motor RX
 *
 *  For more information about communicating to IQ Motor Modules please go to:
 *  http://iq-control.com/documentation
 *    
 *  Created       2019/3/6 by Matthew Piccoli
 *  Last updated  2019/3/6 by Matthew Piccoli
 *  
 *  This example code is in the public domain.
 */

#include <iq_module_communicaiton.hpp>

 // USER SETABLE VALUES HERE---------------------------------------------------
// Sets the angle to go to in radians
const float kAngle = 12.0f*PI;
// Sets the trajectory time in seconds
const float kTime = 5;
// END USER SETABLE VALUES-----------------------------------------------------

// Make an IqSerial object using Serial0 (same as Serial)
IqSerial ser(Serial2); // Motor is controlled via Serial2, so Serial can be used for debugging
// Make a MultiTurnAngleControlClient to interface with a motor module (ID 0)
MultiTurnAngleControlClient angle(0);

void setup() {
  // Initialize the Serial peripheral for motor controller
  ser.begin(115200);
  
  Serial.begin(115200); // added for debugging
  
  // The motor must already be powered on and booted up
  //   for these setup messages to be received.

  // Set custom PID values
  ser.set(angle.angle_Kp_,0.5f);
  ser.set(angle.angle_Ki_,0.0f);
  ser.set(angle.angle_Kd_,0.0f);

  // Send first message
  sendTrajectory(kTime, kAngle);
  sendTrajectory(kTime, 0);
  
}

void loop() {
  print_mode(); // grab the motor, so it needs more than 10 seconds to finish the 2 trajectorys 
}

void sendTrajectory(float time_cmd, float angle_cmd)
{
  // Generate the set messages
  ser.set(angle.trajectory_angular_displacement_,angle_cmd);
  ser.set(angle.trajectory_duration_,time_cmd);
}

void print_mode(){
  uint8_t mode_print = 0;
  ser.get(angle.ctrl_mode_, mode_print);
  Serial.print("mode: \t");
  Serial.println(mode_print);
}
```

**Expected behavior**
I expect, that I can monitor if the motor has finished the programmed trajectory. At least I would like to sense, if the motor is blocked by anything, e.g. by monitoring the current or the current velocity.

**Screenshots**
none

**Board (please describe what board you are using):** see above, ESP32

**Additional context**
I bought this motor for a specific kinetic task, to avoid additional sensors. If the motor cannot tell me about the actual state, I could have used a stepper motor.
Examples would be helpful. Maybe you could publish more Arduino examples, e.g. to read out the current or current velocity.
Furthermore, if the behaviour of the mode variable is a bug, it would be great if it could be resolved soon :)

Additional question: the motor alsways draws ~40 mA @ 12 V when idle or in coast mode. Is there a way to switch off the motor completely and switch it on later via a serial command?

**Comment by iq-matt** [comment]
Hi gon0,

The behavior you're describing is the expected behavior.  You sent the motor 10s worth of trajectories, and after 10s the motor told you the trajectories were finished.  After the 10s, the motor falls back into angle control mode at the last position (as you said, shifting the ctrl_mode from 6 to 5).   

The confusion I think is in the definition of trajectory mode.  The trajectory mode according to the motors is that the position, velocity, and acceleration TARGETs are being computed as a function of time according to the trajectory specifications.  The controller's mode has no notion of whether the motor reached its target.  

You can check if the motor reached its target using other methods though.  Once the ctrl_mode goes from 6 to 5, you can ask the motor its position, and see if it matches (within your tolerance) the end position of the trajectory:
```
float position_now = NAN;
ser.get(angle.obs_angular_displacement_, position_now);
if(position_now < 0.5f && position_now > -0.5f)
  reached_destination = true;
```

You can also check the input current, motor current, or motor torque:
 ```
BrushlessDriveClient mot(0);
PowerMonitorClient pwr(0);

float input_current_now = NAN;
float motor_current_now = NAN;
float motor_torque_now = NAN;

ser.get(pwr.amps_, input_current_now );
ser.get(mot.est_motor_amps_, motor_current_now);
ser.get(mot.est_motor_torque_, motor_torque_now);
```

As for your power draw question, the motor does switch off when you put it in coast mode.  The controller remains on, and the 40mA draw is what it takes to keep the microcontroller and position sensor running.  We currently don't have any of the power saving features enabled on the microcontroller, so there's room for improvement in the future, but we we would have to keep most of the systems turned on to keep track of the position in case the motor is externally actuated.  

EDIT: changed est_motor_amp_ to est_motor_amps_ for posterity.

**Comment by gon0** [comment]
Hi iq-matt,

thank you for your reply. The examples really helped me! I have integrated your examples into my code. I think I forgot to mention that I am using the position firmware.

On Arduino compile I receive this error:
```
error: 'class BrushlessDriveClient' has no member named 'est_motor_amp_'
     ser.get(mot.est_motor_amp_, motor_current_now);
```
"est_motor_amp_" is the exact same typing as in the documentation. Maybe check for typing mistakes?
For me this is not a problem, because I am fine with "input_current_now" and "motor_torque_now".

Thank you for your help!

Best regards,
gon0

**Comment by iq-matt** [comment]
Hi gon0,

You're absolutely right!  The documentation spelled it wrong.  It should be est_motor_amps_. Plural.  Oops.  I'll fix that.  Thank you for letting me know.

-Matt
